### ISSUE TITLE
next line removed with visual mode formatting

### ISSUE THREAD

**Issue by jkozdon** [kdheepak/JuliaFormatter.vim#12]
8dd2d4345f258e3db8d294e84467ba41d7fd4349 seems to have caused the next line in visual mode formatting to be removed.

**Comment by kdheepak** [comment]
Sorry about that, I thought about that and I thought I tested it but I must have missed it.

Reverted in https://github.com/kdheepak/JuliaFormatter.vim/commit/3615586141c536244a1a7e96656c8b54daed7322 and fixed in https://github.com/kdheepak/JuliaFormatter.vim/commit/55c3260ad2dee1b0f2d6be57655c67ca5522c616.
